name: Build
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '18'

            # Speed up subsequent runs with caching
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # Install required deps for action
            - name: Install Dependencies
              run: npm install

            # Finally, build the chrome extension
            - name: Build Chrome Extension
              env:
                  MASTER_PASSPHRASE: ${{ secrets.MASTER_PASSPHRASE }}
                  ETHOS_BASE_URL: ${{ secrets.ETHOS_BASE_URL }}
                  GROWTHBOOK_API_KEY: ${{ secrets.GROWTHBOOK_API_KEY }}
              run: npm run build:prod

            # Archive build artifacts
            - name: Archive build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '18'

            # Speed up subsequent runs with caching
            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # Install required deps for action
            - name: Install Dependencies
              run: npm install

            # Finally, build the chrome extension
            - name: Build Chrome Extension
              run: npm test
